version: 3
updates:
- package-ecosystem: "docker"
  directory: "/images"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "nuget"
  directory: "/src"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "npm"
  directory: "/src/Misc/expressionFunc/hashFiles"
  schedule:
    interval: "daily" 
  target-branch: "main" 
  allow:
  - dependency-type: direct
  - dependency-type: production # check only dependencies, which are going to the compiled app, not supporting tools like @vue-cli
