name: Publish Linux Runner Images New

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch to run the workflow on'
        default: 'main'
      targetPlatform:
        type: string
        description: 'TargetPlatform to build'
        default: 'linux/amd64'
      imageName:
        type: choice
        description: Which image(s) to build (i.e., the corresponding Dockerfile name)
        default: 'all'
        options:
          - all
          - ubuntu-22.04
          - ubuntu-22.04-physical
          - ubuntu-24.04
      runnerVersion:
        type: string
        description: 'Runner app version'
      imageTag:
        type: string
        description: 'Image tag'

env:
  HOST_TMP_TOOL_CACHE: hosttmptoolcache
  PYTHON_TOOLCACHE_VERSION: '3.13.3'

jobs:
  select-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      include: ${{ steps.generate-matrix.outputs.include }}
      distrolist: ${{ steps.generate-matrix.outputs.distrolist }}
    steps:
      - name: Generate matrix based on input
        id: generate-matrix
        uses: actions/github-script@v6
        env:
          INPUT_IMAGENAME: ${{ github.event.inputs.imageName }}
        with:
          script: |
            const imageName = process.env.INPUT_IMAGENAME;
            const allConfigs = [
              { imageName: 'ubuntu-22.04', runs_on: 'raw-ubuntu-22.04', distro: 'ubuntu-22.04' },
              { imageName: 'ubuntu-22.04-physical', runs_on: 'raw-ubuntu-22.04', distro: 'ubuntu-22.04' },
              { imageName: 'ubuntu-24.04', runs_on: 'raw-ubuntu-24.04', distro: 'ubuntu-24.04' }
            ];

            let include = [];
            if (imageName === 'all') {
              include = allConfigs;
            } else {
              const selectedConfig = allConfigs.find(config => config.imageName === imageName);
              if (selectedConfig) {
                include.push(selectedConfig);
              }
            }

            const distrolist = [...new Set(include.map(item => item.distro))];
            
            console.log('Generated include matrix:', JSON.stringify(include, null, 2));
            console.log('Generated distrolist:', JSON.stringify(distrolist, null, 2));

            core.setOutput('include', JSON.stringify(include));
            core.setOutput('distrolist', JSON.stringify(distrolist));

  prepare-toolcache:
    needs: select-matrix
    if: ${{ needs.select-matrix.outputs.include != '[]' }}
    strategy:
      matrix:
        distro: ${{ fromJSON(needs.select-matrix.outputs.distrolist) }}
    runs-on: ${{ matrix.distro }} # runs on GitHub-hosted runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - name: Setup Python for toolcache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_TOOLCACHE_VERSION }}

      # Ref:https://docs.github.com/en/enterprise-server@3.15/admin/managing-github-actions-for-your-enterprise/managing-access-to-actions-from-githubcom/setting-up-the-tool-cache-on-self-hosted-runners-without-internet-access 
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache_${{ matrix.distro }}.tar.gz *

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          name: toolcache-${{ matrix.distro }}
          path: ${{ runner.tool_cache }}/tool_cache_${{ matrix.distro }}.tar.gz

  build:
    needs: [select-matrix, prepare-toolcache]
    if: ${{ needs.select-matrix.outputs.include != '[]' }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.select-matrix.outputs.include) }}
    runs-on: ${{ matrix.runs_on }} # runs on self-hosted runner
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: github-action-runners/${{ matrix.imageName }}
    steps:
      - name: Show all inputs and matrix context
        run: |
          echo "Workflow inputs: ${{ toJSON(github.event.inputs) }}"
          echo "Matrix context: ${{ toJSON(matrix) }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Download tool cache artifact
        uses: actions/download-artifact@v4
        with:
          name: toolcache-${{ matrix.distro }}
          path: ./toolcache_artifact
      
      - name: Unpack tool cache to docker context
        run: |
          mkdir -p ./images/${HOST_TMP_TOOL_CACHE}
          tar -xzf ./toolcache_artifact/tool_cache_${{ matrix.distro }}.tar.gz -C ./images/${HOST_TMP_TOOL_CACHE}

      - name: Compute image version
        id: image
        uses: actions/github-script@v6
        env:
          RUNNER_VERSION: ${{ github.event.inputs.runnerVersion }}
        with:
          script: |
            const fs = require('fs');
            const inputRunnerVersion = process.env.RUNNER_VERSION;
            if (inputRunnerVersion) {
              console.log(`Using input runner version ${inputRunnerVersion}`)
              core.setOutput('version', inputRunnerVersion);
              return
            }
            const runnerVersion = fs.readFileSync('${{ github.workspace }}/src/runnerversion', 'utf8').replace(/\n$/g, '')
            console.log(`Using runner version ${runnerVersion}`)
            core.setOutput('version', runnerVersion);

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ github.event.inputs.imageName == 'all' || github.event.inputs.imageName == matrix.imageName }}
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./images
          file: ./images/Dockerfile.${{ matrix.imageName }}
          platforms: |
            ${{ github.event.inputs.targetPlatform }}
          tags: |
            ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.imageTag }}
          build-args: |
            RUNNER_VERSION=${{ steps.image.outputs.version }}
            TARGETPLATFORM=${{ github.event.inputs.targetPlatform }}
            HOST_TMP_TOOL_CACHE=${{ env.HOST_TMP_TOOL_CACHE }}
          push: true
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description=https://github.com/actions/runner/releases/tag/v${{ steps.image.outputs.version }}
            org.opencontainers.image.licenses=MIT
          cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to:   type=registry,ref=${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max